from aiohttp import web

from .handlers import (
    handle_article,
    handle_bangumi,
    handle_credential_info,
    handle_dynamic_detail,
    handle_dynamic_feed,
    handle_ep,
    handle_get_follow_groups,
    handle_live_feed,
    handle_live_room,
    handle_login_check,
    handle_login_url,
    handle_media,
    handle_my_followings,
    handle_my_info,
    handle_opus,
    handle_refresh_credential,
    handle_user_articles,
    handle_user_card,
    handle_user_dynamic,
    handle_user_info,
    handle_user_live,
    handle_user_videos,
    handle_video,
    handle_video_download,
    health_check,
)


def get_routes():
    return [
        web.post("/video", handle_video),
        web.post("/bangumi", handle_bangumi),
        web.post("/article", handle_article),
        web.post("/live_room", handle_live_room),
        web.post("/login_url", handle_login_url),
        web.post("/login_check", handle_login_check),
        web.post("/user_dynamic", handle_user_dynamic),
        web.post("/user_live", handle_user_live),
        web.post("/user_videos", handle_user_videos),
        web.post("/user_articles", handle_user_articles),
        web.post("/dynamic_detail", handle_dynamic_detail),
        web.post("/opus", handle_opus),
        web.post("/ep", handle_ep),
        web.post("/media", handle_media),
        web.post("/user_info", handle_user_info),
        web.post("/user_card", handle_user_card),
        web.post("/my_followings", handle_my_followings),
        web.post("/my_info", handle_my_info),
        web.post("/get_follow_groups", handle_get_follow_groups),
        web.post("/dynamic_feed", handle_dynamic_feed),
        web.post("/live_feed", handle_live_feed),
        web.post("/credential_info", handle_credential_info),
        web.post("/refresh_credential", handle_refresh_credential),
        web.post("/video_download", handle_video_download),
        web.get("/health", health_check),
    ]

